### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by andreaslarssen** [wemakecustom/symfony-acl-bundle#2]
Hi.

Seems like a great project, but as it is my first time trying to implement ACL in Symfony, a few examples or code blocks explaining configuration would be much appreciated!

**Comment by lemoinem** [comment]
Hello,

Unfortunately, this bundle is abandoned right now. ACL has been removed from Symfony Core with Symfony 3.0. For most use cases, [Symfony Voters][voters] will be powerful enough that you will be able to do without ACLs. If you actually need ACLs, please refer to the [official documentation][ACLs], you'll have to `composer require symfony/security-acl` manually though.

[voters]: http://symfony.com/doc/current/cookbook/security/voters.html
[ACLs]: http://symfony.com/doc/current/cookbook/security/acl.html
