### ISSUE TITLE
Minimum version of symfony

### ISSUE THREAD

**Issue by PurpleBabar** [wemakecustom/symfony-acl-bundle#3]
Hi there :)

Two things i'd like to know :)

what is the minimum version of symfony to use your bundle ?
Are you open to people copying your bundle and maintaining it ? (i'd like to fork it in my organization and work on it :) )

Thx for your answer :smiley:

**Comment by lemoinem** [comment]
Hi, this was developed as part of an unofficial Symfony Hack day, but was never finished.
If you intend to use it, please, by all mean, fork it and run with it. Either a PR or publishing the result would be greatly appreciated, if you feel like it!

The intended Symfony minimum version was most probably 2.3 (the earliest LTS that has reached EOL yet).
